A-kirami/KiramiBot

- kirami/service/controller.py
当事件响应器的优先级为0，且为临时响应器时，不接受控制器检查
事件响应器操作如 `got`、`reject` 等，会创造一个新的临时响应器，这个临时响应器没有经过服务化，在尝试通过 `Ability.got` 获取时会出现 `KeyError` 错误
> 🐛 修复控制器在遭遇事件操作响应器时出现的错误

- kirami/service/subject.py
移除了主体提取器的 state 参数
Permission 不支持 state 注入
> 🐛 修复主体提取器无法在 Permission 中使用的问题

- kirami/config/config.py
将 `Config.load` 重命名为 `Config.load_config`
`Config.load` 的语义不够清晰
> 💥 重命名 `Config` 的加载配置方法

- kirami/utils/utils.py
在 utils 模块中添加转换时间为人类易读的时间格式的工具函数
> ✨ 添加转换时间为易读格式的工具函数

- kirami/depends.py
- kirami/permission.py
- kirami/service/controller.py
新增用于获取用户角色的依赖注入 `useUserRole`
减少重复代码同时便于使用
> ✨ 添加获取用户角色的依赖注入

- kirami/permission.py
- kirami/service/access.py
- kirami/service/controller.py
允许与角色名称进行比较
```py
Role >= "name"
```
新增 `Role.check` 方法用于判断角色是否满足
```py
Role.check("name")
```
简化 Role 的使用
> ✨ 简化 Role 的比较和检查

- kirami/log.py
修改了日志文件名以支持随日期变化
当日期变更时，没有新建新的日志文件
> 🐛 修复日志文件名不会随日期变化的问题

- kirami/log.py
> ✨ 从 `kirami.log` 模块导出 `logger`

- kirami/log.py
改为从 `loguru` 中导出 `Logger` 类型
`loguru._logger.Logger` 缺少类型注解
> 🐛 修复 `kirami.log.logger` 的类型问题

- kirami/utils/utils.py
> ✨ `get_humanize_time` 的 `time` 参数支持更多类型

- kirami/utils/webwright.py
捕获 `SystemExit` 异常
没有捕获 `SystemExit` 异常，导致安装成功时也会导致程序退出
> 🐛 修复 Playwright 安装时未捕获异常的问题

- kirami/utils/utils.py
- `get_path` 支持获取目录路径
- `get_path` 不再检查文件或目录是否存在
- `load_data` 移除参数默认值
> ♻️ 重构工具函数 `get_path` 与 `load_data`

- kirami/config/config.py
- kirami/depends.py
- kirami/permission.py
- kirami/service/__init__.py
- kirami/service/access.py
- kirami/service/controller.py
- kirami/service/manager.py
- kirami/service/service.py
- kirami/service/subject.py
> ♻️ 重构权限控制系统

- kirami/depends.py
- kirami/patch.py
此依赖注入可使得从 state 获得的参数具有相应的类型
通过 state 获取的内容缺少类型
> ✨ 添加获取会话状态内容的依赖注入

- kirami/__init__.py
> ♻️ 重构基础辅助函数

- kirami/__init__.py
- kirami/server/server.py
> 🐛 修复启用调试时没有打印 API 文档链接的问题

- kirami/config/config.py
> 💫 更新 Bot driver 默认配置

- kirami/__init__.py
> ✨ 没有加载成功的插件时不展示加载成功日志

- kirami/utils/webwright.py
安装浏览器之后没有启动，导致 `get_browser` 方法返回 None
> 🐛 修复浏览器安装后没有启动的问题

- kirami/log.py
> ✨ 日志消息添加代码行号

- kirami/utils/renderer/template/github-markdown.css
> 🐛 修复 markdown 代码块超出宽度的问题

- kirami/__init__.py
> 🏷️ 修复依赖更新后的类型错误

- kirami/message.py
- kirami/utils/utils.py
> ✨ 添加文件路径判断工具函数

- kirami/database/__init__.py
- kirami/utils/scheduler.py
- kirami/utils/webwright.py
> ✨ 优化内置启动和停止钩子应用函数的日志

- kirami/utils/webwright.py
> 🐛 修复浏览器关闭时的日志位置错误问题

- kirami/message.py
> ♻️ 改进 `MessageSegment` 中的 `file` 参数处理

- kirami/matcher.py
在 `MatcherCase` 中添加了 `__setattr__` 方法
此错误导致 `on_time` 辅助函数没有正确添加 rule，创建的响应器会响应所有的定时器事件
> 🐛 修复 `MatcherCase` 属性存取问题

- kirami/utils/webwright.py
重构了 `install_browser` 函数，优化了安装体验
> ♻️ 重构 webwright 浏览器安装

- kirami/utils/webwright.py
添加了 `browser.is_connected()` 检查，并移除了 `playwright.stop()`
部分情况下 playwright 会导致进程无法结束
> 🐛 修复部分情况下无法结束进程的问题

- kirami/__init__.py
将 `kirami.log` 的导入提到最前
保证一致的错误日志效果
> ✨ 优先调整日志显示效果

- kirami/log.py
现在当日志文件配置为列表时，每个等级的日志文件中仅保留当前等级的日志，而不是这个等级及以上等级的日志
当前日志保存逻辑不合理
> ✨ 优化日志文件保存逻辑
